#POST http://localhost:8080/api/register?username=test&password=123456
#Content-Type: application/x-www-form-urlencoded
POST http://localhost:8080/api/login?username=test&password=123456
Content-Type: application/x-www-form-urlencoded


